### ISSUE TITLE
`ACS712::readCurrentAC` takes too much time to calculate value.

### ISSUE THREAD

**Issue by CAHEK7** [amperka/TroykaCurrent#1]
200ms is overkill delay to sample 50Hz AC.
Basically you have to sample only one signal period to get its minimum and maximum values, so for 50Hz minimum sampling time is 20ms. To take 20% frequency instability and cover 40Hz AC you can use 25ms sampling time and it will be 8 times faster than initial 200ms.
Also in case minimum and maximum search more samples doesn't mean better results, this is opposite to `ACS712::readCurrentDC` where you calculate average value.

I would suggest to reduce AC sampling time to 25ms. Any thoughts?

**Comment by nomad605dis** [comment]
Hi!

Yes I agree with you. The time should be reduced. But a little time. I tested on different numbers of periods. I think the stay at the 3 periods. And that the time spent will be 60 milliseconds.

**Comment by CAHEK7** [comment]
Ok, 60ms seems reasonable. Thanks.
